server:
  port: 0

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:h2:tcp://localhost/~/user-service
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: true

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.appliction.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

greeting:
  message: Welcome to the UserService

token:
  secret: user_secret # todo 임의의 문자열
  access-token-expiration-time: 900000 # todo 15분 1000(ms) x 60(s) x 15(m)
  refresh-token-expiration-time: 1209600000 # todo 2주 1000(ms) x 60 (s) x 60(m) x 24(h) x 14(d)
