server:
  port: 8080
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: GateWayBaseMsg
            preLogger: true
            postLogger: true
      routes:
        - id: http://localhost:8081/
          predicates:
            - Path=/first-service/**
          filters:
            - CustomFilter
